---
openapi: 3.0.3
info:
  title: onecx-parameters v1
  version: "1.0.0"
servers:
- url: http://onecx-parameter/
tags:
- name: parameter
paths:
  /v1/{productName}/{appId}/history:
    post:
      security:
        - oauth2: [ ocx-pa-me:write ]
      tags:
      - parameter
      description: Create Bucket request
      operationId: bucketRequest
      parameters:
      - name: productName
        in: path
        required: true
        schema:
          type: string
      - name: appId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametersBucket'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParametersBucket'
        "404":
          description: Not Found
  /v1/{productName}/{appId}/parameters:
    get:
      security:
        - oauth2: [ ocx-pa-ap:read ]
      tags:
      - parameter
      description: Get parameters by application id
      operationId: getApplicationParameters
      parameters:
      - name: productName
        in: path
        required: true
        schema:
          type: string
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "404":
          description: Not Found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-pa-ap:read: Grants read access to application parameters
            ocx-pa-me:write: Grants write access to parameter metrics
  schemas:
    ParameterInfo:
      type: object
      properties:
        count:
          format: int64
          type: integer
        type:
          type: string
        defaultValue:
          type: string
        currentValue:
          type: string
    ParametersBucket:
      type: object
      properties:
        parameters:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ParameterInfo'
        instanceId:
          type: string
        start:
          format: date-time
          type: string
          example: 2022-03-10T12:15:50-04:00
        end:
          format: date-time
          type: string
          example: 2022-03-10T12:15:50-04:00
