deployment:
  svc: true
  bff: true
  ui: true
  operator: true

product:
  info:
    data:
      description: "OneCX Parameter"
      imageUrl: ""
      iconName: "pi-sitemap"
      displayName: "OneCX Parameter"
      basePath: "/parameter"
      
